### ISSUE TITLE
No layered jar support in buildpacks right now

### ISSUE THREAD

**Issue by jonashackt** [jonashackt/spring-boot-buildpack#2]
For more details see https://github.com/paketo-buildpacks/spring-boot/issues/1#issuecomment-719676622 . Will be fixed in https://github.com/buildpacks/lifecycle/issues/455 , since it's something like a general bug in https://github.com/buildpacks/lifecycle - not the specific spring boot build pack.

**Comment by nebhale** [comment]
Don't forget to update that screenshot in the readme now that layering works again! 😜 

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/60754/98327976-9bdfc680-1fa9-11eb-992c-d4686f010bbb.png">

**Comment by jonashackt** [comment]
Hey @nebhale thanks for the feedback and great support with that issue - I just thought, I don't fully get it, but then it was a bug :) Really cool to see it fixed! Will update the repo soon - and will also blog about the topic in the next weeks. Also an internal DevFriday will be held with that topic as well - and I also want to spam some Meetups... Please continue your great work 👏
